export const defaultOptions = {
  reverse: false,
  max: 25,
  perspective: 1000,
  scale: 1.1,
  speed: 1000,
  transition: true,
  axis: null,
  reset: true,
  easing: "cubic-bezier(.03,.98,.52,.99)",
};

export const projectItem = [
  {
    id: 1,
    title: "New Portfolio",
    desc: "threejs와 motion-framer를 활용하여 새롭게 만든 포트폴리오 사이트입니다.",
    webPage: "https://",
    github: "https://github.com/paryuyu/new-portfolio.git",
    period: ["2023-07-10", "2023-07-13"],
    images: ["/project-image/newportfolio/new1.png",
      "/project-image/newportfolio/new2.png",
      "/project-image/newportfolio/new3.png",
      "/project-image/newportfolio/new4.png",
      "/project-image/newportfolio/new5.png",
    ],
    skills: ["react-three-fiber & drei", "React.js", "JavaScript", "css", "GitHub", "Framer Motion"],
    people: "단독 프로젝트"
  },
  {
    id: 2,
    title: "00Blog",
    desc: "Nextjs를 활용하여 만든 블로그 사이트입니다.",
    webPage: "https://00blog.vercel.app",
    github: "https://github.com/paryuyu/00blog.git",
    period: ["2023-06-28", "2023-07-10"],
    images: ["/project-image/blog/blog1.png", "/project-image/blog/blog2.png", "/project-image/blog/blog3.png"],
    skills: ["Next.js", "MongoDB", "GitHub", "Tailwind CSS", "JavaScript", "react-quill"],
    people: "단독 프로젝트"
  },
  {
    id: 3,
    title: "promptopia clone",
    desc: "nextjs 13 버전의 문법을 익히기 위해 간단히 진행한 토이프로젝트입니다.",
    webPage: "https://next13-new-promptopia.vercel.app",
    github: "https://github.com/paryuyu/promptopia-clone.git",
    period: ["2023-06-25", "2023-06-27"],
    images: ["/project-image/promptopia/promptopia1.png", "/project-image/promptopia/promptopia2.png", "/project-image/promptopia/promptopia3.png",],
    skills: ["Next.js", "MongoDB", "GitHub", "Tailwind CSS", "JavaScript"],
    people: "단독 프로젝트"
  },
  {
    id: 4,
    title: "Portfolio",
    desc: "nextjs 이전 버전으로 작성했던 포트폴리오 사이트입니다. 이력서 및 이전에 진행했던 토이 프로젝트들을 확인해보실 수 있습니다.",
    webPage: "https://yuyu-resume-developer.vercel.app/",
    github: "",
    period: ["2023-06-28", "2023-07-10"],
    images: ["/project-image/resume/resume1.png",
      "/project-image/resume/resume2.png",
      "/project-image/resume/resume3.png",
      "/project-image/resume/resume4.png",
      "/project-image/resume/resume5.png",
      "/project-image/resume/resume6.png",
      "/project-image/resume/resume7.png",
      "/project-image/resume/resume8.png",
      "/project-image/resume/resume9.png",
      "/project-image/resume/resume10.png",
      "/project-image/resume/resume11.png",
      "/project-image/resume/resume12.png",
      "/project-image/resume/resume13.png",
    ],
    skills: ["Next.js", "MongoDB", "GitHub", "Material-UI", "TypeScript"],
    people: "단독 프로젝트"
  },
];